### ISSUE TITLE
Jumping verse numbers

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon-scans/hariv#1]
@Andhrabharati  In a note, you mentioned that the Hariv. index might have 
some bugs, similar to those solved for [MBh](https://github.com/sanskrit-lexicon-scans/mbhcalc/issues/1).

> BTW, I recall that the Harivamsa (Clc. ed.) also had the "jumping verse numbers" issue as this MBh., and a similar correction can be derived there as well.

Any further information on problems with the Hariv. index?

**Comment by Andhrabharati** [comment]
Looked at my index file and noted it to contain "Remarks" at 15 lines (pages).

However, checked that none of these affect the linking process (**Jim having taken action from the posts in Hariv. indexing by Kate those days**).

So, this issue can be closed.

**Comment by funderburkjim** [comment]
Thanks for checking.
Closing issue.
